version: '3'
services:
    postgres:
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=secret
    redis:
        image: redis:latest
        ports:
            - 6379:6379